artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  dataset_dir: artifacts/data_ingestion/kidney-ct-scan-image
  status_file: artifacts/data_validation/status.txt
  report_file: artifacts/data_validation/validation_report.json


data_transformation:
  root_dir: artifacts/data_transformation
  dataset_dir: artifacts/data_ingestion/kidney-ct-scan-image
  status_file: artifacts/data_validation/status.txt
  transformed_dir: artifacts/data_transformation/transformed_data


training:
  root_dir: artifacts/training
  dataset_dir: artifacts/data_transformation/transformed_data
  mlflow_tracking_uri: http://localhost:5000
  mlflow_experiment_name: Kidney_Disease_Classification

  model_dir: artifacts/training/model
  model_name: best_model.pth

  save_best_only: True
  monitor_metric: val_accuracy

  early_stopping: True
  patience: 5


evaluation:
  root_dir: artifacts/evaluation
  dataset_dir: artifacts/data_transformation/transformed_data
  mlflow_tracking_uri: http://localhost:5000
  mlflow_experiment_name: Kidney_Disease_Classification

  model_path: artifacts/training/model/best_model.pth
  report_file: artifacts/evaluation/evaluation_report.json
  confusion_matrix_file: artifacts/evaluation/confusion_matrix.json


xai:
  root_dir: artifacts/xai
  model_path: artifacts/training/model/best_model.pth
  mlflow_tracking_uri: http://localhost:5000
  mlflow_experiment_name: Kidney_Disease_Classification

  dataset_dir: artifacts/data_transformation/transformed_data
  output_dir: artifacts/xai/gradcam_outputs
  num_samples: 20


prediction:
  model_path: artifacts/training/model/best_model.pth